# Generated by Django 5.0 on 2024-03-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lot', models.TextField()),
                ('appid', models.TextField()),
                ('appname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerPatchDetailsAudit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.TextField(blank=True, null=True)),
                ('uploadid', models.TextField(blank=True, null=True)),
                ('runid', models.TextField(blank=True, null=True)),
                ('hostname', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('defaultuser', models.TextField(blank=True, null=True)),
                ('defaultpass', models.TextField(blank=True, null=True)),
                ('osmake', models.TextField(blank=True, null=True)),
                ('osversion', models.TextField(blank=True, null=True)),
                ('latestpatch', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('instance', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkippedServers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uploadid', models.TextField(blank=True, null=True)),
                ('hostname', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_runid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uploadid', models.TextField(blank=True, null=True)),
                ('runid', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uploadmaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploadid', models.TextField(blank=True, null=True)),
                ('uploadedby', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerPatchDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uploadid', models.TextField(blank=True, null=True)),
                ('runid', models.TextField(blank=True, null=True)),
                ('hostname', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('defaultuser', models.TextField(blank=True, null=True)),
                ('defaultpass', models.TextField(blank=True, null=True)),
                ('osmake', models.TextField(blank=True, null=True)),
                ('osversion', models.TextField(blank=True, null=True)),
                ('latestpatch', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patchservers.instance')),
            ],
        ),
    ]
