# Generated by Django 5.0 on 2024-03-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchservers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRebootDetailsAudit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.TextField(blank=True, null=True)),
                ('uploadid', models.TextField(blank=True, null=True)),
                ('runid', models.TextField(blank=True, null=True)),
                ('hostname', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('crref', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('instance', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerRebootDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uploadid', models.TextField(blank=True, null=True)),
                ('runid', models.TextField(blank=True, null=True)),
                ('hostname', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('crref', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patchservers.instance')),
            ],
        ),
    ]
