# Generated by Django 4.2.7 on 2024-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchservers', '0004_skippedservers_old_uploadid'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverpatchdetails',
            name='uptime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
